"""
Django settings for patrol_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0f4$v*^k&wwuw0!dio!xgd&b(-d_fsre_=kcshan2gr@b9a^#!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '147.93.27.224', 'unmentholated-konner-authorisable.ngrok-free.dev']

# Application definition

INSTALLED_APPS = [
    'daphne',  # for socket
    'channels', # for socket channel
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'authapp',
    'scheduler',
    'checkin',
    'tourlog',
    'dashboard',
    'payslip',
    'reports',  # Added for Celery tasks
    'corsheaders',
    'incident',
    'django_celery_beat',
    'livetracking',  # Sokcet app
    ]

# Socker config

ASGI_APPLICATION = 'patrol_backend.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Socket cofig end

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'dashboard.middleware.AuditActorMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


CORS_ALLOW_ALL_ORIGINS = True

#CORS_ALLOWED_ORIGINS = [
#    "https://evergreenms.cloudgentechnologies.com",
#     "http://localhost:5173",
#     "http://localhost:8001",
#     "http://147.93.27.224:8001",
#     "http://147.93.27.224",       # frontend on port 80
#     "http://147.93.27.224:80",    # explicit port 80
#     "http://147.93.27.224:443",   # if HTTPS later
# ]

ROOT_URLCONF = 'patrol_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'patrol_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'u547203012_gmsdb',
#         'USER': 'u547203012_gmsusr',
#         'PASSWORD': 'Dob@29061983',
#         'HOST': '193.203.184.6',
#         'PORT': '3306',
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'dj_db_conn_pool.backends.mysql',  # Use connection pool backend
        'NAME': 'u547203012_gmsdb',
        'USER': 'u547203012_gmsusr',
        'PASSWORD': 'Dob@29061983',
        'HOST': '193.203.184.6',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 20,
            'read_timeout': 30,
            'write_timeout': 30,
            'charset': 'utf8mb4',
        },
        # Connection pool settings
        'POOL_OPTIONS': {
            'POOL_SIZE': 5,        # Keep 5 connections in pool
            'MAX_OVERFLOW': 10,     # Allow up to 10 extra connections
            'POOL_RECYCLE': 3600,   # Recycle connections after 1 hour
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

# Timezone settings - Enable timezone support
# All datetimes stored in UTC, converted to user timezone for display
USE_TZ = True  # Enable timezone support
TIME_ZONE = 'UTC'  # Store everything in UTC in database

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'authapp.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),         # ⬅️ Extend as needed
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FACE_IDENTIFY_LOG_PHOTOS_ENABLED = False
FACE_IDENTIFY_LOG_ASYNC = True  # write logphoto in background (faster API response)
# 1:N kiosk identification — margin check stops wrong-user; tolerance allows haircut/appearance drift
FACE_IDENTIFY_TOLERANCE = 0.45  # relaxed pass (quality retry / appearance change e.g. haircut)
FACE_IDENTIFY_TOLERANCE_STRICT = 0.38  # fast-path instant accept when clearly best match
FACE_IDENTIFY_MIN_MARGIN = 0.055  # best must beat 2nd place (main wrong-user guard)
FACE_IDENTIFY_TOP_K = 3
FACE_IDENTIFY_REJECT_MULTIPLE_FACES = True
# Quality encode only when fast 640px detect finds no face (blur / distance)
FACE_IDENTIFY_QUALITY_RETRY = True
FACE_IDENTIFY_MAX_IMAGE_WIDTH = 960
FACE_IDENTIFY_UPSAMPLE = 1
FACE_IDENTIFY_NUM_JITTERS = 1

# Kiosk face_attendance performance
FACE_KIOSK_FAST_PATH = True
FACE_KIOSK_MAX_IMAGE_WIDTH = 640
FACE_KIOSK_NUM_JITTERS = 0
FACE_KIOSK_UPSAMPLE = 0
FACE_KIOSK_LIGHT_RESPONSE = True
FACE_KIOSK_DEFER_METRICS_REFRESH = True
# Skip per-punch sibling row reconcile on kiosk (heavy); full metrics refresh runs in background.
FACE_KIOSK_SKIP_SIBLING_RECONCILE = True
# Ignore duplicate kiosk scans for the same guard within N seconds (one row / one log).
FACE_KIOSK_DUPLICATE_PUNCH_SECONDS = 15
# Minimum minutes from check-in before checkout is allowed (kiosk + mobile).
FACE_KIOSK_MIN_CHECKOUT_MINUTES = 5
# Minimum minutes after checkout before a new check-in is allowed (kiosk + mobile).
FACE_KIOSK_MIN_CHECKIN_AFTER_CHECKOUT_MINUTES = 1
# If fast detect fails (common on some phones: EXIF/glare/tilt), retry stronger detect
FACE_KIOSK_DETECT_RETRY = True
FACE_KIOSK_RETRY_UPSAMPLE = 1
FACE_KIOSK_RETRY_MAX_IMAGE_WIDTH = 1280
FACE_KIOSK_RETRY_NUM_JITTERS = 1
FACE_KIOSK_FULL_MAX_IMAGE_WIDTH = 0  # 0 = no downscale on final attempt
FACE_KIOSK_FULL_UPSAMPLE = 1

# Twilio credentials
# TWILIO_SID = 'AC2f6c622ec954be8536e4b4ae1a913e90'
TWILIO_SID = 'ACf6536d328a204ec62b62648f58e17263'
TWILIO_AUTH_TOKEN = 'd06e6cbf817377658ad96c672d3e5c68'
# TWILIO_AUTH_TOKEN = '8c0b864a3d79371cbbdb9571c4c8964b'

# Twilio phone numbers
# TWILIO_PHONE = '+12543453221'  # Twilio voice-enabled number
TWILIO_PHONE = '+916369070815'  # Twilio voice-enabled number
TWILIO_WHATSAPP_NUMBER = '+14155238886'  # Twilio sandbox WhatsApp number

# Admin contact
ADMIN_PHONE = '+918946066577'  # Admin's mobile number for voice call
ADMIN_WHATSAPP = '+918946066577'  # Admin's WhatsApp number

# Email Configuration - Hostinger SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True  # Use SSL for port 465
EMAIL_HOST_USER = 'ravit@cloudgentechnologies.com'
EMAIL_HOST_PASSWORD = 'Yayaya#143'
DEFAULT_FROM_EMAIL = 'ravit@cloudgentechnologies.com'

# For development/testing, you can use console backend instead:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config( 
  cloud_name = 'dtinhrjd1', 
  api_key = '255461719934117', 
  api_secret = 'DB1glK8yEP0nmpH9nCO8UFt-BOQ' 
)

# =====================================================
# CELERY CONFIGURATION
# =====================================================
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Using Redis as message broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Store task results in Redis
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kolkata'  # For scheduled tasks (can be changed per task)
CELERY_ENABLE_UTC = True  # Use UTC for Celery to match Django
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Celery Beat Schedule Configuration
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # 'send-daily-checkin-report': {
    #     'task': 'reports.tasks.email_daily_checkin_report',
    #     # 'schedule': crontab(hour=8, minute=0),  # Run every day at 8:00 AM
    #     # Alternative schedules:
    #     'schedule': crontab(hour=23, minute=59),  # Daily at 11:59 PM
    #     # 'schedule': crontab(minute='*/2'),  # Every 5 minutes (for testing)
    #     # 'schedule': crontab(hour='*/2'),  # Every 2 hours
    #     # 'schedule': crontab(day_of_week='monday', hour=9, minute=0),  # Every Monday at 9 AM
    # },
    # 'send-monthly-attendance-summary': {
    #     'task': 'reports.tasks.email_monthly_attendance_summary',
    #     'schedule': crontab(day_of_month=1, hour=0, minute=30),  # 1st of every month at 12:30 AM
    #     # This runs on the 1st day of each month and reports on the previous month
    #     # Alternative schedules:
    #     # 'schedule': crontab(day_of_month=1, hour=9, minute=0),  # 1st of month at 9:00 AM
    #     # 'schedule': crontab(minute='*/5'),  # Every 5 minutes (for testing)
    # },
    'mark-missed-checkout-v3': {
        'task': 'dashboard.tasks.mark_missed_checkout_v3',
        'schedule': crontab(minute='*/5'),
    },
    'cleanup-old-media-files': {
        'task': 'dashboard.tasks.cleanup_old_media_files',
        'schedule': crontab(day_of_week="Sunday", hour=0,minute=0),
    },
}

# Use Django DB backend for Celery Beat schedule (recommended for production)
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'  # Commented out to use simple scheduler

# =====================================================
# LOGGING CONFIGURATION
# =====================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Custom loggers for our apps
        'dashboard': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'scheduler': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'checkin': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'authapp': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'livetracking': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)
