# Generated by Django 5.2.6 on 2026-08-25 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('scheduler', '0021_assignment_daily_site_guard_site_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReportEmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('recipients', models.TextField(blank=True, default='', help_text='Comma-separated recipient email addresses')),
                ('send_time', models.TimeField(help_text='Local org timezone clock time to send matching reports')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_email_config', to='scheduler.location')),
            ],
            options={
                'verbose_name': 'Location report email config',
                'verbose_name_plural': 'Location report email configs',
            },
        ),
        migrations.CreateModel(
            name='LocationReportEmailItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(choices=[('checkin', 'Check-in Report'), ('attendance', 'Attendance Report'), ('rollcall', 'Roll Call Report'), ('incident', 'Incident Report'), ('visitor_entries', 'Visitor Entries'), ('vehicle_movement', 'Vehicle Movement'), ('monthly_attendance', 'Monthly Attendance Summary'), ('monthly_location', 'Monthly Location Summary')], max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('schedule_type', models.CharField(choices=[('daily', 'Every day'), ('weekly_sunday', 'Every Sunday'), ('monthly_start', '1st of month')], default='daily', max_length=32)),
                ('daily_period', models.CharField(choices=[('previous_day', 'Previous day'), ('today', 'Today')], default='previous_day', help_text='Used only when schedule_type=daily', max_length=32)),
                ('send_pdf', models.BooleanField(default=True)),
                ('send_excel', models.BooleanField(default=False)),
                ('site_wise', models.BooleanField(default=False, help_text='If true, generate one attachment set per active site')),
                ('last_sent_schedule_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.locationreportemailconfig')),
            ],
            options={
                'verbose_name': 'Location report email item',
                'verbose_name_plural': 'Location report email items',
                'unique_together': {('config', 'report_code')},
            },
        ),
        migrations.CreateModel(
            name='ReportEmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_code', models.CharField(max_length=64)),
                ('schedule_key', models.CharField(max_length=64)),
                ('period_label', models.CharField(blank=True, default='', max_length=128)),
                ('formats', models.CharField(blank=True, default='', max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('error', 'Error')], default='sent', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_email_logs', to='scheduler.location')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_email_logs', to='scheduler.locationsite')),
            ],
            options={
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['location', 'report_code', 'schedule_key'], name='reports_rep_locatio_c82cc5_idx')],
            },
        ),
    ]
