# Generated by Django 5.2.6 on 2025-10-11 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('scheduler', '0009_location_latitude_location_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('checkin', 'Check-In'), ('checkout', 'Check-Out')], max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.assignment')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.location')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.shift')),
            ],
        ),
    ]
