# Generated by Django 5.2.6 on 2025-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_checkinlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecheckin',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('checked_out', 'Checked Out'), ('Pending Check-Out', 'Pending Check-Out'), ('Missed Check-Out', 'Missed Check-Out'), ('Missed Check-In', 'Missed Check-In'), ('Delay Check-In', 'Delay Check-In')], default='absent', max_length=20),
        ),
    ]
