# Generated by Django 5.2.6 on 2026-02-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_attendancecheckin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecheckin',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('checked_out', 'Checked Out')], default='absent', max_length=20),
        ),
    ]
