# Generated by Django 5.2.6 on 2026-03-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_attendancecheckin_edit_audit_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globalauditlog',
            new_name='dashboard_g_app_lab_7e7664_idx',
            old_name='dashboard_g_app_lab_ab52b4_idx',
        ),
        migrations.RenameIndex(
            model_name='globalauditlog',
            new_name='dashboard_g_locatio_1c24fd_idx',
            old_name='dashboard_g_locatio_67c7a6_idx',
        ),
        migrations.RenameIndex(
            model_name='globalauditlog',
            new_name='dashboard_g_event_t_f1df29_idx',
            old_name='dashboard_g_event_t_6d76bf_idx',
        ),
    ]
