# Generated by Django 5.2.6 on 2026-04-23 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_attendanceweekoff'),
        ('scheduler', '0017_locationsite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceweekoff',
            new_name='dashboard_a_locatio_bd039d_idx',
            old_name='dashboard_a_locatio_7c8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='attendanceweekoff',
            new_name='dashboard_a_user_id_17ac66_idx',
            old_name='dashboard_a_user_id_8d9e0b_idx',
        ),
        migrations.AddField(
            model_name='attendancecheckin',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='scheduler.locationsite'),
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_logs', to='scheduler.locationsite'),
        ),
        migrations.AlterField(
            model_name='attendancecheckin',
            name='pa_status',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('OW', 'On Work'), ('M', 'Missed Checkout'), ('LD', 'Less Duration'), ('A', 'Absent (Legacy)')], db_index=True, max_length=3, null=True),
        ),
    ]
