# Generated by Django 5.2.6 on 2025-10-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_user_created_at_remove_user_updated_at_and_more'),
        ('scheduler', '0008_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='scheduler.location'),
        ),
    ]
