# Generated by Django 5.2.6 on 2025-10-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_no',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guard', 'Guard'), ('so', 'So'), ('fo', 'Fo')], default='guard', max_length=32),
        ),
    ]
