# Generated by Django 5.2.6 on 2025-10-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_user_aadhar_no_alter_user_email_alter_user_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
