# Generated by Django 5.2.6 on 2026-03-31 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_user_timezone'),
        ('scheduler', '0015_checklist_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='guard', max_length=32),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='True if this is a system default role (Admin, SO, FO, Guard)')),
                ('is_allow_webapp', models.BooleanField(default=False, help_text='True if this role allows web panel access')),
                ('pages', models.JSONField(blank=True, default=list, help_text="List of menu strings (e.g., ['Dashboard', 'Users'])")),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='scheduler.location')),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
    ]
