# Generated by Django 5.2.6 on 2026-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_user_role_role'),
        ('scheduler', '0015_checklist_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('location', 'employee_code')},
        ),
    ]
