# Generated by Django 5.2.6 on 2026-09-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_role_edit_create_access'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersite',
            new_name='authapp_use_user_id_52d367_idx',
            old_name='authapp_use_user_id_site_idx',
        ),
    ]
