# Generated by Django 5.2.6 on 2026-07-16 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0019_remove_locationsite_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_date', models.DateField(help_text='Logical shift start day (overnight-safe)')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('start_photo', models.ImageField(upload_to='roll_call_starts/')),
                ('end_photo', models.ImageField(blank=True, null=True, upload_to='roll_call_ends/')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollcall_sessions_deleted', to=settings.AUTH_USER_MODEL)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollcall_sessions_ended', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollcall_sessions', to='scheduler.location')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollcall_sessions', to='scheduler.shift')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollcall_sessions_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['location', 'shift', 'status'], name='rollcall_ro_locatio_8ad208_idx'), models.Index(fields=['location', 'shift', 'shift_date'], name='rollcall_ro_locatio_1c8167_idx'), models.Index(fields=['status', 'shift_date'], name='rollcall_ro_status_5572d5_idx')],
            },
        ),
    ]
