# Generated by Cursor on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rollcall", "0001_initial"),
        ("scheduler", "0021_assignment_daily_site_guard_site_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="rollcallsession",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rollcall_sessions",
                to="scheduler.locationsite",
            ),
        ),
    ]
