# Generated by Django 5.2.6 on 2025-09-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
