# Generated by Django 5.2.6 on 2025-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_checkpoint_latitude_checkpoint_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='checkpoints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
