# Generated by Django 5.2.6 on 2025-09-21 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_shift_checkpoints_shift_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='checkpoints',
        ),
        migrations.AddField(
            model_name='assignment',
            name='checkpoints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
