# Generated by Django 5.2.6 on 2025-09-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_shift_checkpoints_assignment_checkpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.location'),
        ),
    ]
