# Generated by Django 5.2.6 on 2025-10-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_checkpointtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointtemplate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_templates', to='scheduler.location'),
        ),
    ]
