# Generated by Django 5.2.6 on 2026-02-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_checkpointtemplate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='checkpoint_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_shifts', to='scheduler.checkpointtemplate'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
