# Generated by Django 5.2.6 on 2026-02-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_shift_checkpoint_template_shift_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='scheduler.location'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='sitesetting',
            unique_together={('key', 'location')},
        ),
    ]
