# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_sitesetting_location_alter_sitesetting_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_qr_scan_enable',
            field=models.BooleanField(default=True),
        ),
    ]
