# Generated by Django 5.2.6 on 2026-04-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_locationsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationsite',
            old_name='site_name',
            new_name='name',
        ),
    ]
