# Generated by Django 5.2.6 on 2026-04-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_rename_site_name_locationsite_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsite',
            name='radius',
        ),
    ]
