# Generated by Django 5.2.6 on 2026-08-18 06:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_location_is_ai_extraction_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDailySite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_sites', to='scheduler.assignment')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sites', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignment_sites', to='scheduler.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='scheduler.locationsite')),
            ],
            options={
                'indexes': [models.Index(fields=['guard', 'date'], name='scheduler_a_guard_i_95f6f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('guard', 'date'), name='uniq_daily_site_guard_date')],
            },
        ),
        migrations.CreateModel(
            name='GuardSiteCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_cache', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_site_cache', to='scheduler.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_site_cache', to='scheduler.locationsite')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['guard', 'date', 'created_on'], name='scheduler_g_guard_i_36256f_idx')],
            },
        ),
    ]
