# Generated by Django 5.2.6 on 2026-09-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_sitesetting_propagate_to_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='boundary_enabled',
            field=models.BooleanField(default=False, help_text='Per-site on/off for boundary monitoring (shape is kept when off)'),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='boundary_polygon',
            field=models.JSONField(blank=True, help_text='List of [lat, lng] points when boundary_type=polygon', null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='boundary_radius_m',
            field=models.PositiveIntegerField(blank=True, help_text='Meters from center; used when boundary_type=circle', null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='boundary_type',
            field=models.CharField(choices=[('none', 'None'), ('circle', 'Circle'), ('polygon', 'Polygon')], default='none', max_length=16),
        ),
    ]
