# Generated by Django 5.2.6 on 2026-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_sitecamera'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitecamera',
            new_name='scheduler_s_site_id_89d22b_idx',
            old_name='scheduler_s_site_id_cam_en_idx',
        ),
        migrations.AddField(
            model_name='sitecamera',
            name='anpr_geometry',
            field=models.JSONField(blank=True, default=dict, help_text='Optional ANPR ROI/line, e.g. {"roi":{"x1":0,"y1":0.3,"x2":1,"y2":1},"line":{"x1":0,"y1":0.55,"x2":1,"y2":0.55}}'),
        ),
    ]
