# Generated by Django 5.2.6 on 2026-01-29 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0011_checkpointtemplate_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_user_locations', to='scheduler.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Live Location',
                'verbose_name_plural': 'User Live Locations',
            },
        ),
        migrations.CreateModel(
            name='UserLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_history_records', to='scheduler.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location History',
                'verbose_name_plural': 'User Location History',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='livetrackin_user_id_5988f0_idx'), models.Index(fields=['location', 'timestamp'], name='livetrackin_locatio_0331da_idx')],
            },
        ),
    ]
