# Generated by Django 5.2.6 on 2026-09-01 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_rename_authapp_use_user_id_site_idx_authapp_use_user_id_52d367_idx'),
        ('dashboard', '0016_attendancecheckin_unique_shift_day'),
        ('livetracking', '0001_initial'),
        ('scheduler', '0023_locationsite_boundary_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlivelocation',
            name='assigned_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_user_locations', to='scheduler.locationsite'),
        ),
        migrations.AddField(
            model_name='userlivelocation',
            name='boundary_state',
            field=models.CharField(blank=True, choices=[('inside', 'Inside'), ('outside', 'Outside'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='userlivelocation',
            name='is_inside_boundary',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlivelocation',
            name='last_location_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrackingAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('boundary_breach', 'Boundary breach'), ('location_missing', 'Location missing'), ('manual_sos', 'Manual SOS')], db_index=True, max_length=32)),
                ('subject_role', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_alerts', to='dashboard.attendancecheckin')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_alerts', to='scheduler.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_alerts', to='scheduler.locationsite')),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_alerts_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userlivelocation',
            name='active_breach_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_live_locations', to='livetracking.trackingalert'),
        ),
        migrations.CreateModel(
            name='TrackingAlertRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('websocket', 'WebSocket'), ('in_app', 'In-app')], default='in_app', max_length=16)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='livetracking.trackingalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_alert_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteAlertRecipientConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_boundary_breach', models.BooleanField(default=False)),
                ('notify_location_missing', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_alert_configs', to='authapp.role')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_recipient_configs', to='scheduler.locationsite')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'notify_boundary_breach'], name='livetrackin_site_id_ccd13d_idx'), models.Index(fields=['site', 'notify_location_missing'], name='livetrackin_site_id_eb41c6_idx')],
                'unique_together': {('site', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['location', 'is_active', 'created_at'], name='livetrackin_locatio_c2ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['site', 'alert_type', 'is_active'], name='livetrackin_site_id_7140a5_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingalert',
            index=models.Index(fields=['subject_user', 'is_active'], name='livetrackin_subject_38aa44_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingalertrecipient',
            index=models.Index(fields=['user', 'read_at'], name='livetrackin_user_id_9f76c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackingalertrecipient',
            unique_together={('alert', 'user', 'channel')},
        ),
    ]
