"""Shared dashboard-style PDF header (title, date, company) + footer on every page."""
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Table, TableStyle

PDF_FOOTER_TEXT = "Generated by CloudGen Technologies"


def _fmt_report_date(d):
    if not d:
        return ""
    if hasattr(d, "strftime"):
        return d.strftime("%b %d %Y")
    return str(d)


def draw_dashboard_pdf_header_and_footer(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica-Oblique", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.drawCentredString(
        doc.leftMargin + doc.width / 2.0,
        0.15 * inch,
        PDF_FOOTER_TEXT,
    )
    canvas.drawRightString(
        doc.leftMargin + doc.width,
        0.15 * inch,
        f"Page {canvas.getPageNumber()}",
    )

    org_name = getattr(doc, "org_name", "—")
    dept_label = getattr(doc, "dept_label", org_name)
    range_start = getattr(doc, "range_start", None)
    range_end = getattr(doc, "range_end", None)
    printed_at = getattr(doc, "printed_at", None)
    title = getattr(doc, "report_title", "Report")

    styles = getSampleStyleSheet()

    def _para_style(name, **kwargs):
        base = dict(
            leftIndent=0,
            rightIndent=0,
            firstLineIndent=0,
            spaceBefore=0,
            spaceAfter=0,
        )
        base.update(kwargs)
        return ParagraphStyle(name, **base)

    title_style = _para_style(
        "DashPdfTitle",
        parent=styles["Normal"],
        fontSize=11,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    )
    date_style = _para_style(
        "DashPdfDate",
        parent=styles["Normal"],
        fontSize=9,
        alignment=TA_CENTER,
    )
    meta_style = _para_style(
        "DashPdfMeta",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=11,
    )
    meta_right_style = _para_style(
        "DashPdfMetaRight",
        parent=meta_style,
        alignment=TA_RIGHT,
    )

    title_p = Paragraph(title, title_style)
    if range_start and range_end:
        date_line = f"{_fmt_report_date(range_start)} To {_fmt_report_date(range_end)}"
    else:
        date_line = getattr(doc, "date_range_display", "") or "—"
    date_p = Paragraph(date_line, date_style)
    printed_text = ""
    if printed_at:
        printed_text = f"Printed On : {printed_at.strftime('%b %d %Y %H:%M')}"

    header_meta = Table(
        [
            [
                Paragraph(f"Company &nbsp; {org_name}", meta_style),
                Paragraph(printed_text, meta_right_style),
            ],
            [Paragraph(f"Site &nbsp; {dept_label}", meta_style), ""],
        ],
        colWidths=[doc.width * 0.55, doc.width * 0.45],
    )
    header_meta.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    header_meta.hAlign = "LEFT"

    top_y = doc.height + doc.bottomMargin + doc.topMargin
    title_p.wrap(doc.width, doc.topMargin)
    title_p.drawOn(canvas, doc.leftMargin, top_y - 18)
    date_p.wrap(doc.width, doc.topMargin)
    date_p.drawOn(canvas, doc.leftMargin, top_y - 32)
    header_meta.wrap(doc.width, doc.topMargin)
    header_meta.drawOn(canvas, doc.leftMargin, top_y - 75)

    canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
    canvas.setLineWidth(0.75)
    canvas.line(doc.leftMargin, top_y - 80, doc.leftMargin + doc.width, top_y - 80)

    canvas.restoreState()
