"""Quick Pay Report PDF — hourly and monthly sections."""
from __future__ import annotations

import os
from io import BytesIO

from django.conf import settings
from django.utils import timezone

from payslip.hourly_wage_summary_excel import HOURLY_COLUMNS, MONTHLY_COLUMNS

PDF_FOOTER_TEXT = "Generated by CloudGen Technologies"


def _draw_pdf_footer(canvas, doc):
    from reportlab.lib import colors
    from reportlab.lib.units import inch

    canvas.saveState()
    canvas.setFont("Helvetica-Oblique", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.drawCentredString(
        doc.leftMargin + doc.width / 2.0,
        0.15 * inch,
        PDF_FOOTER_TEXT,
    )
    canvas.restoreState()


def _build_section_table(columns, rows, content_width, header_style, cell_style):
    from reportlab.lib import colors
    from reportlab.platypus import Paragraph, Table, TableStyle

    col_labels = [label for label, _ in columns]
    col_keys = [key for _, key in columns]
    col_count = len(columns)
    col_width = content_width / col_count if col_count else content_width

    numeric_keys = {"rate", "worked_hours", "salary", "gross_salary", "paid_days"}

    def _cell_val(row, key):
        val = row.get(key, "")
        if key in numeric_keys:
            if key == "paid_days":
                return f"{float(val):.2f}" if val is not None else ""
            return f"{float(val):.2f}" if val is not None else ""
        return str(val or "")

    table_data = [[Paragraph(lbl, header_style) for lbl in col_labels]]
    if rows:
        for row in rows:
            table_data.append(
                [
                    Paragraph(_cell_val(row, key).replace("&", "&amp;"), cell_style)
                    for key in col_keys
                ]
            )
    else:
        table_data.append(
            [Paragraph("No employees in this section.", cell_style)]
            + [""] * (col_count - 1)
        )

    tbl = Table(table_data, colWidths=[col_width] * col_count, repeatRows=1)
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E1F2")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("FONTSIZE", (0, 1), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 3),
                ("RIGHTPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    tbl.hAlign = "LEFT"
    return tbl


def build_hourly_wage_summary_pdf_bytes(context):
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=0.35 * inch,
        rightMargin=0.35 * inch,
        topMargin=0.4 * inch,
        bottomMargin=0.45 * inch,
    )
    content_width = doc.width
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "QuickPayTitle",
        parent=styles["Normal"],
        fontSize=12,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        spaceAfter=8,
    )
    section_style = ParagraphStyle(
        "QuickPaySection",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        spaceBefore=10,
        spaceAfter=6,
    )
    cell_style = ParagraphStyle(
        "QuickPayCell",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=10,
    )
    header_style = ParagraphStyle(
        "QuickPayHeader",
        parent=cell_style,
        alignment=TA_CENTER,
    )

    org_name = context.get("org_name") or ""
    period_label = context.get("period_label") or ""
    hourly_rows = context.get("hourly_rows") or []
    monthly_rows = context.get("monthly_rows") or []

    story = []
    story.append(
        Paragraph(
            f"Quick Pay Report — {org_name}<br/>{period_label}",
            title_style,
        )
    )
    story.append(Spacer(1, 6))

    story.append(Paragraph("Hourly Employees", section_style))
    story.append(
        _build_section_table(
            HOURLY_COLUMNS, hourly_rows, content_width, header_style, cell_style
        )
    )

    story.append(Paragraph("Monthly Employees", section_style))
    story.append(
        _build_section_table(
            MONTHLY_COLUMNS, monthly_rows, content_width, header_style, cell_style
        )
    )

    doc.build(
        story,
        onFirstPage=_draw_pdf_footer,
        onLaterPages=_draw_pdf_footer,
    )
    return buffer.getvalue()


def generate_hourly_wage_summary_pdf_internal(context):
    pdf_bytes = build_hourly_wage_summary_pdf_bytes(context)
    filename = f"quick_pay_report_{timezone.now().strftime('%Y%m%d%H%M%S')}.pdf"
    file_path = os.path.join(settings.MEDIA_ROOT, filename)
    os.makedirs(settings.MEDIA_ROOT, exist_ok=True)
    with open(file_path, "wb") as fh:
        fh.write(pdf_bytes)
    row_count = len(context.get("hourly_rows") or []) + len(context.get("monthly_rows") or [])
    return {
        "file_path": file_path,
        "filename": filename,
        "row_count": row_count,
        "pdf_bytes": pdf_bytes,
    }
