from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scheduler", "0015_checklist_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePayrollProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employee_code", models.CharField(max_length=64)),
                ("salary_type", models.CharField(choices=[("monthly", "Monthly")], default="monthly", max_length=20)),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bank_name", models.CharField(blank=True, max_length=128, null=True)),
                ("account_holder_name", models.CharField(blank=True, max_length=128, null=True)),
                ("account_number", models.CharField(blank=True, max_length=64, null=True)),
                ("ifsc_code", models.CharField(blank=True, max_length=32, null=True)),
                ("branch_name", models.CharField(blank=True, max_length=128, null=True)),
                ("pf_enabled", models.BooleanField(default=False)),
                ("esi_enabled", models.BooleanField(default=False)),
                ("pf_number", models.CharField(blank=True, max_length=64, null=True)),
                ("esi_number", models.CharField(blank=True, max_length=64, null=True)),
                ("uan", models.CharField(blank=True, max_length=64, null=True)),
                ("pan", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payroll_profiles", to="scheduler.location")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payroll_profile", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payroll_profile_created", to=settings.AUTH_USER_MODEL)),
                ("modified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payroll_profile_modified", to=settings.AUTH_USER_MODEL)),
            ],
            options={"indexes": [models.Index(fields=["location", "employee_code"], name="payslip_emp_loc_9d7183_idx"), models.Index(fields=["is_active"], name="payslip_emp_is_acti_d307da_idx")]},
        ),
        migrations.CreateModel(
            name="PayslipFieldConfig",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("config_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payslip_field_configs", to="scheduler.location")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_field_config_created", to=settings.AUTH_USER_MODEL)),
                ("modified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_field_config_modified", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["config_name"]},
        ),
        migrations.CreateModel(
            name="PayslipTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("company_logo", models.ImageField(blank=True, null=True, upload_to="payslip_logos/")),
                ("company_name", models.CharField(blank=True, max_length=200, null=True)),
                ("company_address", models.TextField(blank=True, null=True)),
                ("company_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("company_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("company_gstin", models.CharField(blank=True, max_length=20, null=True)),
                ("header_text", models.CharField(blank=True, max_length=200, null=True)),
                ("header_color", models.CharField(default="#1e40af", max_length=7)),
                ("header_alignment", models.CharField(default="center", max_length=10)),
                ("footer_text", models.TextField(blank=True, null=True)),
                ("footer_color", models.CharField(default="#64748b", max_length=7)),
                ("layout_config", models.JSONField(blank=True, default=dict)),
                ("page_size", models.CharField(default="A4", max_length=10)),
                ("orientation", models.CharField(default="portrait", max_length=10)),
                ("font_size", models.IntegerField(default=10)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("location", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payslip_template", to="scheduler.location")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_template_created", to=settings.AUTH_USER_MODEL)),
                ("modified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_template_modified", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="PayslipField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=100)),
                ("field_code", models.CharField(max_length=50)),
                ("field_type", models.CharField(choices=[("EARNING", "Earning"), ("DEDUCTION", "Deduction"), ("INFO", "Information")], max_length=20)),
                ("value_type", models.CharField(choices=[("PERCENTAGE", "Percentage"), ("FIXED", "Fixed"), ("FORMULA", "Formula")], max_length=20)),
                ("value", models.CharField(max_length=500)),
                ("display_order", models.IntegerField(default=1)),
                ("is_visible", models.BooleanField(default=True)),
                ("default_value", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("field_config", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="payslip.payslipfieldconfig")),
            ],
            options={"ordering": ["display_order"]},
        ),
        migrations.CreateModel(
            name="PayslipRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("month", models.CharField(max_length=7)),
                ("month_days", models.IntegerField(default=0)),
                ("working_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("present_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("half_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("absent_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("paid_days", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("gross_salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_earnings", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("field_values", models.JSONField(blank=True, default=dict)),
                ("attendance_snapshot", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("APPROVED", "Approved"), ("PAID", "Paid")], default="DRAFT", max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("paid_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("paid_on", models.DateTimeField(blank=True, null=True)),
                ("payment_mode", models.CharField(blank=True, choices=[("cash", "Cash"), ("bank", "Bank Transfer"), ("upi", "UPI"), ("other", "Other")], max_length=20, null=True)),
                ("payment_ref_no", models.CharField(blank=True, max_length=128, null=True)),
                ("payment_notes", models.TextField(blank=True, null=True)),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="payslips/")),
                ("field_config", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payslips", to="payslip.payslipfieldconfig")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payslip_records", to="scheduler.location")),
                ("payroll_profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payslips", to="payslip.employeepayrollprofile")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payslips", to="payslip.paysliptemplate")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payslip_records", to=settings.AUTH_USER_MODEL)),
                ("generated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_generated", to=settings.AUTH_USER_MODEL)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_approved", to=settings.AUTH_USER_MODEL)),
                ("paid_marked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payslip_paid_marked", to=settings.AUTH_USER_MODEL)),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-generated_on"], "indexes": [models.Index(fields=["month", "status"], name="payslip_rec_month_a44599_idx"), models.Index(fields=["location", "month"], name="payslip_rec_locatio_b39c44_idx")]},
        ),
        migrations.AlterUniqueTogether(name="employeepayrollprofile", unique_together={("location", "employee_code")}),
        migrations.AlterUniqueTogether(name="payslipfieldconfig", unique_together={("location", "config_name")}),
        migrations.AlterUniqueTogether(name="payslipfield", unique_together={("field_config", "field_code")}),
        migrations.AlterUniqueTogether(name="paysliprecord", unique_together={("user", "month")}),
    ]

