# Generated by Django 5.2.6 on 2026-03-31 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0003_paysliptemplate_header_text_color'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeepayrollprofile',
            new_name='payslip_emp_locatio_2e2a07_idx',
            old_name='payslip_emp_loc_9d7183_idx',
        ),
        migrations.RenameIndex(
            model_name='employeepayrollprofile',
            new_name='payslip_emp_is_acti_1d6671_idx',
            old_name='payslip_emp_is_acti_d307da_idx',
        ),
        migrations.RenameIndex(
            model_name='paysliprecord',
            new_name='payslip_pay_month_3e2ce7_idx',
            old_name='payslip_rec_month_a44599_idx',
        ),
        migrations.RenameIndex(
            model_name='paysliprecord',
            new_name='payslip_pay_locatio_ee6178_idx',
            old_name='payslip_rec_locatio_b39c44_idx',
        ),
    ]
