# Generated by Django 5.2.6 on 2026-04-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0004_rename_payslip_emp_loc_9d7183_idx_payslip_emp_locatio_2e2a07_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employeepayrollprofile',
            name='payslip_emp_locatio_2e2a07_idx',
        ),
        migrations.AlterUniqueTogether(
            name='employeepayrollprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employeepayrollprofile',
            name='employee_code',
        ),
    ]
