"""Roll call Excel / PDF export helpers."""
from datetime import datetime, timedelta
from io import BytesIO

from django.utils import timezone
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font

from patrol_backend.utils.timezone_utils import (
    get_user_timezone_from_request,
    get_user_today,
    to_user_timezone,
)

from .utils import resolve_location_for_request


HEADERS = [
    "Shift Date",
    "Location",
    "Shift",
    "Shift Time",
    "Status",
    "Started By",
    "Started Emp Code",
    "Started At",
    "Ended By",
    "Ended Emp Code",
    "Ended At",
]

PDF_FOOTER_TEXT = "Generated by CloudGen Technologies"


def _fmt_dt(dt, user_tz):
    if not dt:
        return ""
    local = to_user_timezone(dt, user_tz)
    return local.strftime("%d-%b-%Y %H:%M") if local else ""


def _fmt_date(d):
    if not d:
        return ""
    return d.strftime("%d-%b-%Y")


def _fmt_report_date(d):
    if not d:
        return ""
    return d.strftime("%b %d %Y")


def _user_name(user):
    if not user:
        return ""
    return getattr(user, "name", None) or ""


def _user_code(user):
    if not user:
        return ""
    return getattr(user, "employee_code", None) or ""


def _shift_time(shift):
    if not shift:
        return ""
    return f"{shift.start_time}–{shift.end_time}"


def _session_row(session, request):
    location_id = str(session.location_id) if session.location_id else None
    user_tz = get_user_timezone_from_request(request, location_id=location_id)
    return [
        _fmt_date(session.shift_date),
        session.location.name if session.location else "",
        session.shift.name if session.shift else "",
        _shift_time(session.shift),
        (session.status or "").capitalize(),
        _user_name(session.started_by),
        _user_code(session.started_by),
        _fmt_dt(session.started_at, user_tz),
        _user_name(session.ended_by),
        _user_code(session.ended_by),
        _fmt_dt(session.ended_at, user_tz),
    ]


def _resolve_export_meta(request):
    """Company, date range, and printed-on for PDF header (attendance-style)."""
    location_id_param = request.query_params.get("location_id") or request.query_params.get(
        "location"
    )
    location_id, _ = resolve_location_for_request(request, location_id_param)
    if not location_id and location_id_param and location_id_param != "All":
        location_id = str(location_id_param)

    user_tz = get_user_timezone_from_request(request, location_id=location_id)
    user_today = get_user_today(user_tz)
    date_filter = (request.query_params.get("date_filter") or "today").lower()
    start_date = request.query_params.get("start_date")
    end_date = request.query_params.get("end_date")

    range_start = user_today
    range_end = user_today
    if date_filter in ("week", "this_week"):
        range_start = user_today - timedelta(days=user_today.weekday())
        range_end = min(range_start + timedelta(days=6), user_today)
    elif date_filter in ("month", "this_month"):
        range_start = user_today.replace(day=1)
        range_end = user_today
    elif date_filter == "custom" and start_date and end_date:
        try:
            range_start = datetime.strptime(start_date, "%Y-%m-%d").date()
            range_end = min(datetime.strptime(end_date, "%Y-%m-%d").date(), user_today)
        except ValueError:
            pass

    org_name = "—"
    if location_id and location_id != "All":
        from scheduler.models import Location

        loc = Location.objects.filter(id=location_id, is_deleted=False).first()
        if loc:
            org_name = loc.name
    elif getattr(request.user, "location", None):
        org_name = request.user.location.name or "—"

    status_filter = (request.query_params.get("status") or "all").strip().lower()
    printed_at = to_user_timezone(timezone.now(), user_tz)

    return {
        "org_name": org_name,
        "dept_label": org_name,
        "range_start": range_start,
        "range_end": range_end,
        "printed_at": printed_at,
        "status_filter": status_filter,
        "date_filter": date_filter,
    }


def generate_rollcall_excel(queryset, request):
    wb = Workbook()
    ws = wb.active
    ws.title = "Roll Call"
    ws.append(HEADERS)

    header_font = Font(bold=True)
    for cell in ws[1]:
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for session in queryset.order_by("-shift_date", "-started_at"):
        ws.append(_session_row(session, request))

    from openpyxl.utils import get_column_letter

    widths = [14, 22, 14, 18, 10, 18, 14, 18, 18, 14, 18]
    for idx, width in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(idx)].width = width

    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    date_filter = request.query_params.get("date_filter", "today")
    if date_filter == "custom":
        start = request.query_params.get("start_date") or ""
        end = request.query_params.get("end_date") or ""
        filename = f"rollcall_report_{start}_{end}.xlsx"
    else:
        filename = f"rollcall_report_{timezone.now().strftime('%Y%m%d')}.xlsx"
    return buffer.getvalue(), filename


def _draw_rollcall_pdf_header_and_footer(canvas, doc):
    """Attendance-style repeating header + footer on every page."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, Table, TableStyle

    canvas.saveState()

    canvas.setFont("Helvetica-Oblique", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.drawCentredString(
        doc.leftMargin + doc.width / 2.0,
        0.15 * inch,
        PDF_FOOTER_TEXT,
    )
    canvas.drawRightString(
        doc.leftMargin + doc.width,
        0.15 * inch,
        f"Page {canvas.getPageNumber()}",
    )

    org_name = getattr(doc, "org_name", "—")
    dept_label = getattr(doc, "dept_label", "—")
    range_start = getattr(doc, "range_start", None)
    range_end = getattr(doc, "range_end", None)
    printed_at = getattr(doc, "printed_at", None)

    styles = getSampleStyleSheet()

    def _para_style(name, **kwargs):
        base = dict(
            leftIndent=0,
            rightIndent=0,
            firstLineIndent=0,
            spaceBefore=0,
            spaceAfter=0,
        )
        base.update(kwargs)
        return ParagraphStyle(name, **base)

    title_style = _para_style(
        "HeaderTitle",
        parent=styles["Normal"],
        fontSize=11,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        spaceAfter=2,
    )
    date_style = _para_style(
        "HeaderDate",
        parent=styles["Normal"],
        fontSize=9,
        alignment=TA_CENTER,
        spaceAfter=6,
    )
    meta_style = _para_style(
        "HeaderMeta",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=11,
    )
    meta_right_style = _para_style(
        "HeaderMetaRight",
        parent=meta_style,
        alignment=TA_RIGHT,
    )

    title_p = Paragraph("Roll Call Report (Detailed Summary Report)", title_style)
    date_p = Paragraph(
        f"{_fmt_report_date(range_start)} To {_fmt_report_date(range_end)}",
        date_style,
    )
    printed_text = ""
    if printed_at:
        printed_text = f"Printed On : {printed_at.strftime('%b %d %Y %H:%M')}"

    header_meta = Table(
        [
            [
                Paragraph(f"Company &nbsp; {org_name}", meta_style),
                Paragraph(printed_text, meta_right_style),
            ],
            [Paragraph(f"Site &nbsp; {dept_label}", meta_style), ""],
        ],
        colWidths=[doc.width * 0.55, doc.width * 0.45],
    )
    header_meta.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    header_meta.hAlign = "LEFT"

    top_y = doc.height + doc.bottomMargin + doc.topMargin
    title_p.wrap(doc.width, doc.topMargin)
    title_p.drawOn(canvas, doc.leftMargin, top_y - 18)
    date_p.wrap(doc.width, doc.topMargin)
    date_p.drawOn(canvas, doc.leftMargin, top_y - 32)
    header_meta.wrap(doc.width, doc.topMargin)
    header_meta.drawOn(canvas, doc.leftMargin, top_y - 75)

    canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
    canvas.setLineWidth(0.75)
    canvas.line(doc.leftMargin, top_y - 80, doc.leftMargin + doc.width, top_y - 80)

    canvas.restoreState()


def generate_rollcall_pdf(queryset, request):
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    meta = _resolve_export_meta(request)
    sessions = list(queryset.order_by("-shift_date", "-started_at"))

    buffer = BytesIO()
    left_margin = 0.2 * inch
    right_margin = 0.2 * inch
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=1.2 * inch,
        bottomMargin=0.35 * inch,
    )
    content_width = doc.width

    doc.org_name = meta["org_name"]
    doc.dept_label = meta["dept_label"]
    doc.range_start = meta["range_start"]
    doc.range_end = meta["range_end"]
    doc.printed_at = meta["printed_at"]

    styles = getSampleStyleSheet()

    def _para_style(name, **kwargs):
        base = dict(
            leftIndent=0,
            rightIndent=0,
            firstLineIndent=0,
            spaceBefore=0,
            spaceAfter=0,
        )
        base.update(kwargs)
        return ParagraphStyle(name, **base)

    cell_style = _para_style(
        "RollCallCell",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=11,
    )
    header_cell_style = _para_style(
        "RollCallHeaderCell",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        leading=11,
    )
    summary_style = _para_style(
        "RollCallSummary",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=11,
        spaceBefore=2,
    )

    open_count = sum(1 for s in sessions if s.status == "open")
    closed_count = sum(1 for s in sessions if s.status == "closed")
    status_label = meta["status_filter"]
    if status_label != "all":
        status_display = status_label.capitalize()
    else:
        status_display = "All"

    story = []
    story.append(
        Paragraph(
            f"Status: {status_display}"
            f"&nbsp;&nbsp;&nbsp;&nbsp;"
            f"Filter: {meta['date_filter']}",
            summary_style,
        )
    )
    story.append(Spacer(1, 6))

    header_row = [Paragraph(h, header_cell_style) for h in HEADERS]
    data = [header_row]
    for session in sessions:
        row = _session_row(session, request)
        data.append([Paragraph(str(v) if v else "—", cell_style) for v in row])

    if len(data) == 1:
        empty = [Paragraph("No roll call sessions found", cell_style)] + [""] * (
            len(HEADERS) - 1
        )
        data.append(empty)

    col_ratios = [0.09, 0.12, 0.08, 0.10, 0.06, 0.10, 0.08, 0.10, 0.10, 0.08, 0.09]
    ratio_sum = sum(col_ratios)
    col_widths = [content_width * (r / ratio_sum) for r in col_ratios]

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E1F2")),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("FONTSIZE", (0, 1), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ("ALIGN", (0, 1), (-1, -1), "LEFT"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 3),
                ("RIGHTPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            f"Total Sessions={len(sessions)} , Open={open_count} , Closed={closed_count}",
            summary_style,
        )
    )

    doc.build(
        story,
        onFirstPage=_draw_rollcall_pdf_header_and_footer,
        onLaterPages=_draw_rollcall_pdf_header_and_footer,
    )
    buffer.seek(0)

    date_filter = meta["date_filter"]
    if date_filter == "custom":
        start = request.query_params.get("start_date") or ""
        end = request.query_params.get("end_date") or ""
        filename = f"rollcall_report_{start}_{end}.pdf"
    else:
        filename = f"rollcall_report_{timezone.now().strftime('%Y%m%d')}.pdf"
    return buffer.getvalue(), filename
