# Generated by Django 5.2.6 on 2025-10-14 21:56

import django.db.models.deletion
import django.utils.timezone
import incident.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='incident',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='incident',
        #     name='title',
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='assigned_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='assigned_on',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='assigned_to',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned_to', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='closure_description',
        #     field=models.TextField(default='Incident description not provided', help_text='Details about the incident'),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='created_by',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='created_on',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='incident_description',
        #     field=models.TextField(default='Incident description not provided', help_text='Details about the incident'),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='photo',
        #     field=models.ImageField(blank=True, null=True, upload_to=incident.models.media_upload_path),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='resolved_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='resolved_on',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='severity',
        #     field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='status',
        #     field=models.CharField(choices=[('Open', 'Open'), ('In-Progress', 'In-Progress'), ('Closed', 'Closed')], default='Open', max_length=20),
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='ticket_number',
        #     field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=12, unique=True),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='incident',
        #     name='video',
        #     field=models.FileField(blank=True, null=True, upload_to=incident.models.media_upload_path),
        #),
    ]
