# Generated by Django 5.2.6 on 2025-10-14 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_remove_incident_created_at_remove_incident_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='incident',
            new_name='incidents',
        ),
    ]
