# Generated by Django 5.2.6 on 2025-10-14 22:13

import django.db.models.deletion
import django.utils.timezone
import incident.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_rename_incident_incidents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incidentreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('incident_description', models.TextField(default='Incident description not provided', help_text='Details about the incident')),
                ('closure_description', models.TextField(default='Incident description not provided', help_text='Details about the incident')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=incident.models.media_upload_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=incident.models.media_upload_path)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In-Progress', 'In-Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_on', models.DateTimeField(blank=True, null=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='incidents',
        ),
    ]
