# Generated by Django 5.2.6 on 2025-10-15 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0004_incidentreport_delete_incidents'),
        ('scheduler', '0009_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='scheduler.checkpoint'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='scheduler.location'),
        ),
    ]
