# Generated by Cursor on 2026-03-17

from django.db import migrations, models

from ..models import media_upload_path


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0005_incidentreport_checkpoint_incidentreport_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="description_audio",
            field=models.FileField(blank=True, null=True, upload_to=media_upload_path),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="incident_description",
            field=models.TextField(
                blank=True, default="", help_text="Details about the incident", null=True
            ),
        ),
    ]

