# Generated by Django 5.2.6 on 2026-07-20 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0019_remove_locationsite_radius'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ic_passport_number', models.CharField(db_index=True, max_length=64)),
                ('document_type', models.CharField(choices=[('malaysian_mykad', 'Malaysian MyKad'), ('indian_aadhaar', 'Indian Aadhaar'), ('indian_dl', 'Indian DL'), ('passport', 'Passport'), ('other', 'Other')], default='other', max_length=32)),
                ('visitor_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_deleted', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='scheduler.location')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VisitorEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_type', models.CharField(choices=[('contractor', 'Contractor'), ('client', 'Client'), ('delivery', 'Delivery'), ('guest', 'Guest'), ('other', 'Other')], default='guest', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], db_index=True, default='checked_in', max_length=16)),
                ('purpose_of_visit', models.CharField(blank=True, default='', max_length=500)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=64)),
                ('remarks', models.TextField(blank=True, default='')),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('visit_date_time', models.DateTimeField(blank=True, help_text='Scheduled visit time for invitations', null=True)),
                ('qr_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='visitor_qr/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_deleted', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_hosted', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_entries', to='scheduler.location')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='visitor.visitor')),
            ],
            options={
                'ordering': ['-check_in_time', '-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VisitorAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('visitor_photo', 'Visitor Photo'), ('id_proof', 'ID Proof'), ('exit_photo', 'Exit Photo'), ('vehicle_photo', 'Vehicle Photo'), ('other', 'Other')], max_length=32)),
                ('file', models.FileField(upload_to='visitor_assets/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('visitor_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='visitor.visitorentry')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['location', 'ic_passport_number'], name='visitor_vis_locatio_66b391_idx'),
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['location', 'is_deleted'], name='visitor_vis_locatio_f95e7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('location', 'ic_passport_number'), name='unique_visitor_ic_per_location_active'),
        ),
        migrations.AddIndex(
            model_name='visitorentry',
            index=models.Index(fields=['location', 'status'], name='visitor_vis_locatio_d14d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorentry',
            index=models.Index(fields=['location', 'check_in_time'], name='visitor_vis_locatio_ee218e_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorentry',
            index=models.Index(fields=['status', 'check_in_time'], name='visitor_vis_status_b00e59_idx'),
        ),
    ]
