# Generated by Django 5.2.6 on 2026-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial_visitor_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorasset',
            name='asset_type',
            field=models.CharField(choices=[('visitor_photo', 'Visitor Photo'), ('id_proof', 'ID Proof'), ('exit_photo', 'Exit Photo'), ('vehicle_photo', 'Vehicle Photo'), ('additional', 'Additional'), ('other', 'Other')], max_length=32),
        ),
    ]
