# Generated by Django 5.2.6 on 2026-07-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_add_additional_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='document_type',
        ),
    ]
