# Generated by Django 5.2.6 on 2026-07-21 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_remove_locationsite_radius'),
        ('visitor', '0003_remove_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorentry',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='entry_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('invitation', 'Invitation')], db_index=True, default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='expected_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='expected_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='qr_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='revert_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitorentry',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Invitation only — future visit date', null=True),
        ),
        migrations.AlterField(
            model_name='visitorasset',
            name='asset_type',
            field=models.CharField(choices=[('visitor_photo', 'Visitor Photo'), ('id_proof', 'ID Proof'), ('exit_photo', 'Checkout Image'), ('vehicle_photo', 'Vehicle Photo'), ('additional', 'Additional'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='visitorentry',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('reverted', 'Reverted'), ('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], db_index=True, default='pending_approval', max_length=32),
        ),
        migrations.AlterField(
            model_name='visitorentry',
            name='visit_date_time',
            field=models.DateTimeField(blank=True, help_text='Legacy / optional scheduled datetime for invitations', null=True),
        ),
        migrations.AddIndex(
            model_name='visitorentry',
            index=models.Index(fields=['host', 'status'], name='visitor_vis_host_id_59ec52_idx'),
        ),
    ]
