# Generated by Django 5.2.6 on 2026-07-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_visitorentry_pass_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorentry',
            name='scanned_by',
            field=models.ForeignKey(blank=True, help_text='Guard who scanned invite/scheduled QR into pending_approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_entries_scanned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitorentry',
            name='visit_date',
            field=models.DateField(blank=True, help_text='Visit day — today for manual entry; scheduled date for invitations', null=True),
        ),
    ]
