# Generated by Cursor on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor", "0009_visitorentry_checked_in_by"),
        ("scheduler", "0021_assignment_daily_site_guard_site_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorentry",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitor_entries",
                to="scheduler.locationsite",
            ),
        ),
    ]
