# Generated by Django 5.2.6 on 2026-09-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0011_visitorlookupoption'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visitorlookupoption',
            new_name='visitor_vis_kind_5054f6_idx',
            old_name='visitor_vis_kind_6a8f2d_idx',
        ),
        migrations.AlterField(
            model_name='visitorentry',
            name='entry_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('invitation', 'Invitation'), ('cctv', 'CCTV ANPR')], db_index=True, default='manual', max_length=16),
        ),
    ]
