"""Visitor Excel / PDF export helpers (PDF matches rollcall/dashboard style)."""
from datetime import datetime, timedelta
from io import BytesIO

from django.http import HttpResponse
from django.utils import timezone
from openpyxl import Workbook
from openpyxl.styles import Font

from patrol_backend.utils.timezone_utils import (
    get_user_timezone_from_request,
    get_user_today,
    to_user_timezone,
)

from .utils import resolve_location_for_request

HEADERS = [
    "Visit Date",
    "IC / Passport",
    "Visitor Name",
    "Phone",
    "Company",
    "Visitor Type",
    "Vehicle Type",
    "Status",
    "Vehicle Number",
    "Location",
    "Check In",
    "Check Out",
    "Registered By",
    "Checked In By",
    "Checked Out By",
    "Purpose",
    "Remarks",
]

# Same columns as Excel (landscape PDF)
PDF_HEADERS = list(HEADERS)

PDF_FOOTER_TEXT = "Generated by CloudGen Technologies"


def _fmt_dt(dt, user_tz):
    if not dt:
        return ""
    local = to_user_timezone(dt, user_tz)
    return local.strftime("%d/%m/%Y %H:%M") if local else ""


def _fmt_date(d):
    if not d:
        return ""
    return d.strftime("%d/%m/%Y")


def _fmt_report_date(d):
    if not d:
        return ""
    return d.strftime("%b %d %Y")


def _status_label(status):
    if not status:
        return ""
    if status == "cancelled":
        return "Rejected"
    return (status or "").replace("_", " ").title()


def _entry_export_row(entry, request):
    """Shared row values for Excel and PDF (same columns / order)."""
    location_id = str(entry.location_id) if entry.location_id else None
    user_tz = get_user_timezone_from_request(request, location_id=location_id)
    visitor = entry.visitor
    return [
        _fmt_date(entry.visit_date),
        visitor.ic_passport_number if visitor else "",
        visitor.visitor_name if visitor else "",
        visitor.phone_number if visitor else "",
        entry.company_name or "",
        entry.visitor_type or "",
        entry.vehicle_type or "",
        _status_label(entry.status) if entry.status else "",
        entry.vehicle_number or "",
        entry.location.name if entry.location else "",
        _fmt_dt(entry.check_in_time, user_tz),
        _fmt_dt(entry.check_out_time, user_tz),
        getattr(entry.created_by, "name", "") if entry.created_by else "",
        getattr(entry.checked_in_by, "name", "") if entry.checked_in_by else "",
        getattr(entry.checked_out_by, "name", "") if entry.checked_out_by else "",
        entry.purpose_of_visit or "",
        entry.remarks or "",
    ]


def _entry_excel_row(entry, request):
    return _entry_export_row(entry, request)


def _entry_pdf_row(entry, request):
    return _entry_export_row(entry, request)


def _resolve_export_meta(request):
    """Company, date range, and printed-on for PDF header (rollcall/attendance style)."""
    location_id_param = request.query_params.get("location_id") or request.query_params.get(
        "location"
    )
    location_id, _ = resolve_location_for_request(request, location_id_param)
    if not location_id and location_id_param and location_id_param != "All":
        location_id = str(location_id_param)

    user_tz = get_user_timezone_from_request(request, location_id=location_id)
    user_today = get_user_today(user_tz)
    date_filter = (request.query_params.get("date_filter") or "today").lower()
    start_date = request.query_params.get("start_date")
    end_date = request.query_params.get("end_date")

    range_start = user_today
    range_end = user_today
    if date_filter in ("week", "this_week"):
        range_start = user_today - timedelta(days=user_today.weekday())
        range_end = range_start + timedelta(days=6)
    elif date_filter in ("month", "this_month"):
        range_start = user_today.replace(day=1)
        range_end = user_today
    elif date_filter == "upcoming":
        range_start = user_today
        range_end = user_today + timedelta(days=30)
    elif date_filter == "custom" and start_date and end_date:
        try:
            range_start = datetime.strptime(start_date, "%Y-%m-%d").date()
            range_end = datetime.strptime(end_date, "%Y-%m-%d").date()
        except ValueError:
            pass
    elif date_filter == "all":
        range_start = None
        range_end = None

    org_name = "—"
    if location_id and location_id != "All":
        from scheduler.models import Location

        loc = Location.objects.filter(id=location_id, is_deleted=False).first()
        if loc:
            org_name = loc.name
    elif getattr(request.user, "location", None):
        org_name = request.user.location.name or "—"

    status_filter = (request.query_params.get("status") or "all").strip().lower()
    visitor_type = (
        request.query_params.get("visitor_type")
        or request.query_params.get("visitorType")
        or "all"
    ).strip().lower()
    printed_at = to_user_timezone(timezone.now(), user_tz)

    return {
        "org_name": org_name,
        "dept_label": org_name,
        "range_start": range_start,
        "range_end": range_end,
        "printed_at": printed_at,
        "status_filter": status_filter,
        "visitor_type": visitor_type,
        "date_filter": date_filter,
    }


def generate_visitor_excel(queryset, request):
    wb = Workbook()
    ws = wb.active
    ws.title = "Visitor Entries"
    ws.append(HEADERS)
    for cell in ws[1]:
        cell.font = Font(bold=True)

    for entry in queryset:
        ws.append(_entry_excel_row(entry, request))

    buf = BytesIO()
    wb.save(buf)
    buf.seek(0)

    filename = f"visitor_entries_{timezone.now().strftime('%Y%m%d')}.xlsx"
    response = HttpResponse(
        buf.getvalue(),
        content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    )
    response["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response


def _draw_visitor_pdf_header_and_footer(canvas, doc):
    """Attendance/rollcall-style repeating header + footer on every page."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, Table, TableStyle

    canvas.saveState()

    canvas.setFont("Helvetica-Oblique", 8)
    canvas.setFillColor(colors.HexColor("#64748b"))
    canvas.drawCentredString(
        doc.leftMargin + doc.width / 2.0,
        0.15 * inch,
        PDF_FOOTER_TEXT,
    )
    canvas.drawRightString(
        doc.leftMargin + doc.width,
        0.15 * inch,
        f"Page {canvas.getPageNumber()}",
    )

    org_name = getattr(doc, "org_name", "—")
    dept_label = getattr(doc, "dept_label", "—")
    range_start = getattr(doc, "range_start", None)
    range_end = getattr(doc, "range_end", None)
    printed_at = getattr(doc, "printed_at", None)

    styles = getSampleStyleSheet()

    def _para_style(name, **kwargs):
        base = dict(
            leftIndent=0,
            rightIndent=0,
            firstLineIndent=0,
            spaceBefore=0,
            spaceAfter=0,
        )
        base.update(kwargs)
        return ParagraphStyle(name, **base)

    title_style = _para_style(
        "HeaderTitle",
        parent=styles["Normal"],
        fontSize=11,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        spaceAfter=2,
    )
    date_style = _para_style(
        "HeaderDate",
        parent=styles["Normal"],
        fontSize=9,
        alignment=TA_CENTER,
        spaceAfter=6,
    )
    meta_style = _para_style(
        "HeaderMeta",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=11,
    )
    meta_right_style = _para_style(
        "HeaderMetaRight",
        parent=meta_style,
        alignment=TA_RIGHT,
    )

    title_p = Paragraph("Visitor Entries Report (Detailed Summary Report)", title_style)
    if range_start and range_end:
        date_line = f"{_fmt_report_date(range_start)} To {_fmt_report_date(range_end)}"
    else:
        date_line = "All dates"
    date_p = Paragraph(date_line, date_style)
    printed_text = ""
    if printed_at:
        printed_text = f"Printed On : {printed_at.strftime('%b %d %Y %H:%M')}"

    header_meta = Table(
        [
            [
                Paragraph(f"Company &nbsp; {org_name}", meta_style),
                Paragraph(printed_text, meta_right_style),
            ],
            [Paragraph(f"Department &nbsp; {dept_label}", meta_style), ""],
        ],
        colWidths=[doc.width * 0.55, doc.width * 0.45],
    )
    header_meta.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    header_meta.hAlign = "LEFT"

    top_y = doc.height + doc.bottomMargin + doc.topMargin
    title_p.wrap(doc.width, doc.topMargin)
    title_p.drawOn(canvas, doc.leftMargin, top_y - 18)
    date_p.wrap(doc.width, doc.topMargin)
    date_p.drawOn(canvas, doc.leftMargin, top_y - 32)
    header_meta.wrap(doc.width, doc.topMargin)
    header_meta.drawOn(canvas, doc.leftMargin, top_y - 75)

    canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
    canvas.setLineWidth(0.75)
    canvas.line(doc.leftMargin, top_y - 80, doc.leftMargin + doc.width, top_y - 80)

    canvas.restoreState()


def generate_visitor_pdf(queryset, request):
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    meta = _resolve_export_meta(request)
    entries = list(queryset)

    buffer = BytesIO()
    left_margin = 0.15 * inch
    right_margin = 0.15 * inch
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        leftMargin=left_margin,
        rightMargin=right_margin,
        topMargin=1.2 * inch,
        bottomMargin=0.35 * inch,
    )
    content_width = doc.width

    doc.org_name = meta["org_name"]
    doc.dept_label = meta["dept_label"]
    doc.range_start = meta["range_start"]
    doc.range_end = meta["range_end"]
    doc.printed_at = meta["printed_at"]

    styles = getSampleStyleSheet()

    def _para_style(name, **kwargs):
        base = dict(
            leftIndent=0,
            rightIndent=0,
            firstLineIndent=0,
            spaceBefore=0,
            spaceAfter=0,
        )
        base.update(kwargs)
        return ParagraphStyle(name, **base)

    cell_style = _para_style(
        "VisitorCell",
        parent=styles["Normal"],
        fontSize=6,
        fontName="Helvetica",
        alignment=TA_LEFT,
        leading=7.5,
    )
    header_cell_style = _para_style(
        "VisitorHeaderCell",
        parent=styles["Normal"],
        fontSize=6,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
        leading=7.5,
    )
    summary_style = _para_style(
        "VisitorSummary",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Helvetica-Bold",
        alignment=TA_LEFT,
        leading=10,
        spaceBefore=2,
    )

    pending = sum(1 for e in entries if e.status == "pending_approval")
    checked_in = sum(1 for e in entries if e.status == "checked_in")
    checked_out = sum(1 for e in entries if e.status == "checked_out")
    status_label = meta["status_filter"]
    status_display = "All" if status_label == "all" else _status_label(status_label)
    type_label = meta["visitor_type"]
    type_display = "All" if type_label == "all" else type_label.capitalize()

    story = []
    story.append(
        Paragraph(
            f"Status: {status_display}"
            f"&nbsp;&nbsp;&nbsp;&nbsp;"
            f"Type: {type_display}"
            f"&nbsp;&nbsp;&nbsp;&nbsp;"
            f"Filter: {meta['date_filter']}",
            summary_style,
        )
    )
    story.append(Spacer(1, 6))

    header_row = [Paragraph(h, header_cell_style) for h in PDF_HEADERS]
    data = [header_row]
    for entry in entries:
        row = _entry_pdf_row(entry, request)
        data.append([Paragraph(str(v) if v else "—", cell_style) for v in row])

    if len(data) == 1:
        empty = [Paragraph("No visitor entries found", cell_style)] + [""] * (
            len(PDF_HEADERS) - 1
        )
        data.append(empty)

    # 17 columns matching Excel (no ETA/ETO; Purpose before Remarks)
    col_ratios = [
        0.06,   # Visit Date
        0.06,   # IC
        0.08,   # Visitor
        0.055,  # Phone
        0.055,  # Company
        0.05,   # Visitor Type
        0.055,  # Vehicle Type
        0.055,  # Status
        0.06,   # Vehicle Number
        0.05,   # Location
        0.065,  # Check In
        0.065,  # Check Out
        0.055,  # Registered By
        0.055,  # Checked In By
        0.055,  # Checked Out By
        0.06,   # Purpose
        0.065,  # Remarks
    ]
    ratio_sum = sum(col_ratios)
    col_widths = [content_width * (r / ratio_sum) for r in col_ratios]

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E1F2")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 6),
                ("FONTSIZE", (0, 1), (-1, -1), 6),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (0, 0), (-1, 0), "CENTER"),
                ("ALIGN", (0, 1), (-1, -1), "LEFT"),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("LEFTPADDING", (0, 0), (-1, -1), 1),
                ("RIGHTPADDING", (0, 0), (-1, -1), 1),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 8))
    story.append(
        Paragraph(
            f"Total Entries={len(entries)} , Pending={pending} , "
            f"Checked In={checked_in} , Checked Out={checked_out}",
            summary_style,
        )
    )

    doc.build(
        story,
        onFirstPage=_draw_visitor_pdf_header_and_footer,
        onLaterPages=_draw_visitor_pdf_header_and_footer,
    )
    buffer.seek(0)

    date_filter = meta["date_filter"]
    if date_filter == "custom":
        start = request.query_params.get("start_date") or ""
        end = request.query_params.get("end_date") or ""
        filename = f"visitor_entries_{start}_{end}.pdf"
    else:
        filename = f"visitor_entries_{timezone.now().strftime('%Y%m%d')}.pdf"
    return buffer.getvalue(), filename
